/* ==========================================================================
   PRODUCTS & CATEGORIES
   --------------------------------------------------------------------------
   HOW TO EDIT
   - Change a price:   edit the "price" number (e.g. price: 19.99).
   - Show a sale:      add oldPrice: 24.99 (the original price, shown crossed out).
   - Remove a product: delete its whole { ... } block, including the comma after it.
   - Add a product:    copy an existing block, paste it, and give it a NEW unique "id".
   - Feature on home:  set featured: true.
   - Out of stock:     set inStock: false (customers can still ask about it).
   - Photo:            put the photo in images/products/ and set
                       image: "images/products/your-photo.jpg"
   - "category" must be one of: "car", "truck", "tools".
   - "type" must be one of the type ids listed under that category below.
   - "added" (YYYY-MM-DD) is used for the "Newest" sort option.
   ========================================================================== */

const CATEGORIES = [
  {
    id: "car",
    name: "Car Accessories",
    page: "car-accessories.html",
    description: "Comfort, convenience and safety upgrades for every car.",
    types: [
      { id: "phone-holders", name: "Phone Holders" },
      { id: "car-chargers", name: "Car Chargers" },
      { id: "seat-covers", name: "Seat Covers" },
      { id: "floor-mats", name: "Floor Mats" },
      { id: "air-fresheners", name: "Air Fresheners" },
      { id: "cleaning", name: "Cleaning Products" },
      { id: "emergency", name: "Emergency Equipment" },
    ],
  },
  {
    id: "truck",
    name: "Truck Accessories",
    page: "truck-accessories.html",
    description: "Heavy-duty gear for work trucks and weekend haulers.",
    types: [
      { id: "truck-lights", name: "Truck Lights" },
      { id: "truck-covers", name: "Truck Covers" },
      { id: "tie-downs", name: "Tie-Down Equipment" },
      { id: "utility", name: "Utility Accessories" },
      { id: "truck-interior", name: "Interior Accessories" },
    ],
  },
  {
    id: "tools",
    name: "Tools",
    page: "tools.html",
    description: "Reliable tools for roadside fixes and garage jobs.",
    types: [
      { id: "hand-tools", name: "Hand Tools" },
      { id: "screwdrivers", name: "Screwdrivers" },
      { id: "wrenches", name: "Wrenches" },
      { id: "pliers", name: "Pliers" },
      { id: "tire-tools", name: "Tire Tools" },
      { id: "maintenance", name: "Car Maintenance Tools" },
    ],
  },
];

const PRODUCTS = [
  /* ---------------------------- CAR ACCESSORIES ---------------------------- */
  {
    id: "magnetic-vent-phone-mount",
    name: "Magnetic Vent Phone Mount",
    price: 14.99,
    category: "car",
    type: "phone-holders",
    image: "images/products/phone-holder.svg",
    description: "Strong magnetic mount that clips securely to any air vent.",
    details:
      "Keep your phone in view for navigation without blocking your dashboard. Six N52 magnets hold phones steady over bumps, and the 360° ball joint lets you switch between portrait and landscape in a second.",
    features: ["Fits all vent types", "360° rotation", "Includes 2 metal plates", "One-hand use"],
    featured: true,
    added: "2026-08-14",
    inStock: true,
  },
  {
    id: "dashboard-phone-holder",
    name: "Dashboard & Windshield Phone Holder",
    price: 22.99,
    oldPrice: 27.99,
    category: "car",
    type: "phone-holders",
    image: "images/products/phone-holder.svg",
    description: "Suction-cup holder with an extendable arm for dash or glass.",
    details:
      "A sticky gel suction cup grips textured dashboards and windshields. The telescopic arm extends up to 3 inches so your phone sits exactly where you want it.",
    features: ["Fits 4\"–7\" phones", "Telescopic arm", "Reusable gel suction", "Quick-release button"],
    added: "2026-05-02",
    inStock: true,
  },
  {
    id: "dual-usb-c-car-charger",
    name: "Dual USB-C Fast Car Charger 48W",
    price: 18.99,
    category: "car",
    type: "car-chargers",
    image: "images/products/car-charger.svg",
    description: "Charge two devices at full speed from your 12V socket.",
    details:
      "Compact aluminium charger with two USB-C ports delivering up to 48W total, enough to fast-charge phones and tablets at the same time. Built-in protection against overheating and short circuits.",
    features: ["2× USB-C, 48W total", "Works with 12V & 24V", "Aluminium body", "LED power ring"],
    featured: true,
    added: "2026-09-10",
    inStock: true,
    badge: "New",
  },
  {
    id: "braided-charging-cable-3in1",
    name: "3-in-1 Braided Charging Cable",
    price: 12.99,
    category: "car",
    type: "car-chargers",
    image: "images/products/car-charger.svg",
    description: "One tough cable with USB-C, Lightning and Micro-USB tips.",
    details:
      "A 4 ft nylon-braided cable that charges almost any phone in the car. Reinforced connectors survive daily bending and tugging.",
    features: ["USB-C, Lightning & Micro-USB", "4 ft length", "Nylon braided", "Tangle-free"],
    added: "2026-03-21",
    inStock: true,
  },
  {
    id: "leatherette-seat-cover-set",
    name: "Premium Leatherette Seat Cover Set",
    price: 89.99,
    oldPrice: 109.99,
    category: "car",
    type: "seat-covers",
    image: "images/products/seat-cover.svg",
    description: "Full front & rear set in black with red contrast stitching.",
    details:
      "Water-resistant faux-leather covers that protect your original seats from spills, wear and sun damage. Compatible with side airbags and fits most cars, SUVs and small trucks.",
    features: ["Full 9-piece set", "Airbag compatible", "Water resistant", "Easy wipe clean"],
    featured: true,
    added: "2026-07-01",
    inStock: true,
    badge: "Sale",
  },
  {
    id: "front-seat-covers-mesh",
    name: "Breathable Mesh Front Seat Covers",
    price: 34.99,
    category: "car",
    type: "seat-covers",
    image: "images/products/seat-cover.svg",
    description: "Cool, breathable covers for the two front seats.",
    details:
      "Lightweight 3D mesh keeps you cool on hot days. Elastic straps install in under 10 minutes with no tools.",
    features: ["Pair of front covers", "3D breathable mesh", "Machine washable", "Universal fit"],
    added: "2026-02-11",
    inStock: true,
  },
  {
    id: "all-weather-floor-mats",
    name: "All-Weather Rubber Floor Mats (4 pc)",
    price: 39.99,
    category: "car",
    type: "floor-mats",
    image: "images/products/floor-mat.svg",
    description: "Deep-groove mats that trap mud, snow and spills.",
    details:
      "Heavy-duty odorless rubber with raised edges to keep water and dirt off your carpet. Trim-to-fit lines make them suit almost any vehicle.",
    features: ["Front & rear set", "Trim-to-fit", "Anti-slip backing", "Hose clean"],
    featured: true,
    added: "2026-06-18",
    inStock: true,
  },
  {
    id: "carpet-floor-mats",
    name: "Classic Carpet Floor Mats (4 pc)",
    price: 29.99,
    category: "car",
    type: "floor-mats",
    image: "images/products/floor-mat.svg",
    description: "Soft black carpet mats with a rubber heel pad.",
    details: "A clean, factory look for your interior with a durable heel pad on the driver mat.",
    features: ["Front & rear set", "Heel pad", "Nibbed backing", "Universal fit"],
    added: "2025-12-04",
    inStock: true,
  },
  {
    id: "vent-clip-air-freshener",
    name: "Vent Clip Air Freshener – New Car",
    price: 6.99,
    category: "car",
    type: "air-fresheners",
    image: "images/products/air-freshener.svg",
    description: "Adjustable intensity scent that lasts up to 45 days.",
    details: "A clean 'new car' fragrance with an adjustable dial so you control how strong it is.",
    features: ["Up to 45 days", "Adjustable dial", "Fits most vents"],
    added: "2026-09-25",
    inStock: true,
    badge: "New",
  },
  {
    id: "hanging-diffuser-bottle",
    name: "Hanging Diffuser Bottle – Black Ice",
    price: 9.99,
    category: "car",
    type: "air-fresheners",
    image: "images/products/air-freshener.svg",
    description: "Glass diffuser with a wooden cap and fresh, bold scent.",
    details: "Hang it from your mirror for a long-lasting, subtle fragrance. Refillable glass bottle.",
    features: ["8 ml refillable", "Up to 60 days", "Glass & wood"],
    added: "2026-04-30",
    inStock: true,
  },
  {
    id: "interior-detailer-kit",
    name: "Interior Detailer & Microfiber Kit",
    price: 19.99,
    category: "car",
    type: "cleaning",
    image: "images/products/cleaning.svg",
    description: "Streak-free spray plus 3 premium microfiber towels.",
    details:
      "Safely cleans dashboards, screens, plastics and vinyl with a matte, non-greasy finish. UV protection helps prevent fading.",
    features: ["500 ml spray", "3 microfiber towels", "UV protection", "Fresh scent"],
    featured: true,
    added: "2026-08-02",
    inStock: true,
  },
  {
    id: "waterless-wash-wax",
    name: "Waterless Wash & Wax",
    price: 14.49,
    category: "car",
    type: "cleaning",
    image: "images/products/cleaning.svg",
    description: "Wash and shine your car anywhere – no hose needed.",
    details: "Lifts dust and light dirt while leaving a protective glossy wax layer.",
    features: ["750 ml", "No water needed", "Adds gloss"],
    added: "2026-01-15",
    inStock: true,
  },
  {
    id: "roadside-emergency-kit",
    name: "Roadside Emergency Kit",
    price: 49.99,
    category: "car",
    type: "emergency",
    image: "images/products/emergency.svg",
    description: "Warning triangle, first aid, flashlight, gloves and more.",
    details:
      "Everything you need to stay safe if you break down: reflective warning triangle, 42-piece first-aid kit, LED flashlight, work gloves, tow strap and a compact carry bag.",
    features: ["Warning triangle", "42-pc first aid", "LED flashlight", "Tow strap & gloves"],
    featured: true,
    added: "2026-07-22",
    inStock: true,
  },
  {
    id: "heavy-duty-jumper-cables",
    name: "Heavy-Duty Jumper Cables 16 ft",
    price: 32.99,
    category: "car",
    type: "emergency",
    image: "images/products/jumper-cables.svg",
    description: "4-gauge copper-clad cables with tangle-free storage bag.",
    details: "Long enough to reach between vehicles parked side by side. Solid clamps with insulated grips.",
    features: ["16 ft length", "4 gauge", "Insulated clamps", "Storage bag"],
    added: "2026-03-08",
    inStock: true,
  },

  /* --------------------------- TRUCK ACCESSORIES --------------------------- */
  {
    id: "led-light-bar-32",
    name: "32\" LED Light Bar – Combo Beam",
    price: 129.99,
    oldPrice: 149.99,
    category: "truck",
    type: "truck-lights",
    image: "images/products/light-bar.svg",
    description: "Bright spot & flood combo beam for work and off-road use.",
    details:
      "180W output with a mix of spot and flood beams for long reach and wide coverage. Waterproof IP68 housing, mounting brackets and wiring harness included.",
    features: ["180W, 18,000 lm", "IP68 waterproof", "Wiring harness included", "Stainless brackets"],
    featured: true,
    added: "2026-09-03",
    inStock: true,
    badge: "Sale",
  },
  {
    id: "led-pod-lights",
    name: "LED Pod Lights (Pair)",
    price: 44.99,
    category: "truck",
    type: "truck-lights",
    image: "images/products/light-bar.svg",
    description: "Compact 3\" cube lights for bumpers, mirrors or racks.",
    details: "Small but powerful flood lights, perfect for backing up or lighting a work area.",
    features: ["2 × 18W", "IP67 waterproof", "Flood beam"],
    added: "2026-05-27",
    inStock: true,
  },
  {
    id: "soft-roll-up-tonneau-cover",
    name: "Soft Roll-Up Tonneau Cover",
    price: 249.99,
    category: "truck",
    type: "truck-covers",
    image: "images/products/tonneau-cover.svg",
    description: "Weather-resistant bed cover that rolls up in seconds.",
    details:
      "Protect your cargo from rain and prying eyes. Clamp-on install with no drilling. Ask in store for the right size for your truck.",
    features: ["No-drill install", "Full bed access", "Water resistant vinyl", "Sizes for most trucks"],
    featured: true,
    added: "2026-06-05",
    inStock: true,
  },
  {
    id: "truck-bed-cargo-tarp",
    name: "Heavy-Duty Cargo Tarp 8×10 ft",
    price: 24.99,
    category: "truck",
    type: "truck-covers",
    image: "images/products/tonneau-cover.svg",
    description: "Waterproof tarp with reinforced grommets every 18\".",
    details: "Ideal for covering loose loads, firewood or equipment.",
    features: ["8 × 10 ft", "Waterproof", "Rust-proof grommets"],
    added: "2025-11-19",
    inStock: true,
  },
  {
    id: "ratchet-straps-4pk",
    name: "Ratchet Tie-Down Straps (4 pack)",
    price: 29.99,
    category: "truck",
    type: "tie-downs",
    image: "images/products/ratchet-strap.svg",
    description: "15 ft straps with 1,500 lb break strength and S-hooks.",
    details: "Secure loads quickly with smooth ratchets and coated S-hooks that won't scratch your truck.",
    features: ["4 × 15 ft straps", "1,500 lb break strength", "Coated S-hooks"],
    featured: true,
    added: "2026-08-20",
    inStock: true,
  },
  {
    id: "bungee-cord-assortment",
    name: "Bungee Cord Assortment (24 pc)",
    price: 16.99,
    category: "truck",
    type: "tie-downs",
    image: "images/products/ratchet-strap.svg",
    description: "Assorted lengths with steel hooks for everyday hauling.",
    details: "A mix of 10\", 18\", 24\", 32\" and 40\" cords for any job.",
    features: ["24 pieces", "Steel hooks", "5 lengths"],
    added: "2026-01-29",
    inStock: true,
  },
  {
    id: "truck-bed-tool-box",
    name: "Aluminium Truck Bed Tool Box",
    price: 299.0,
    category: "truck",
    type: "utility",
    image: "images/products/truck-toolbox.svg",
    description: "Lockable diamond-plate box that mounts across the bed.",
    details: "Weatherproof seal and locking latches keep your tools safe and dry. Ask in store for sizing.",
    features: ["Diamond-plate aluminium", "Locking latches", "Weather seal"],
    added: "2026-04-12",
    inStock: false,
  },
  {
    id: "trailer-hitch-ball-mount",
    name: "Trailer Hitch Ball Mount Kit",
    price: 39.99,
    category: "truck",
    type: "utility",
    image: "images/products/truck-toolbox.svg",
    description: "2\" receiver ball mount with 2\" ball, pin and clip.",
    details: "Rated for 7,500 lb towing capacity. Black powder-coated steel.",
    features: ["2\" receiver", "7,500 lb rating", "Pin & clip included"],
    added: "2026-09-18",
    inStock: true,
    badge: "New",
  },
  {
    id: "steering-wheel-cover",
    name: "Leather Steering Wheel Cover",
    price: 19.99,
    category: "truck",
    type: "truck-interior",
    image: "images/products/steering-wheel.svg",
    description: "Non-slip grip cover for 15\"–16\" truck wheels.",
    details: "Soft-touch microfiber leather with red stitching improves grip and comfort on long drives.",
    features: ["Fits 15\"–16\"", "Non-slip", "Breathable"],
    added: "2026-07-09",
    inStock: true,
  },
  {
    id: "seat-back-organizer",
    name: "Seat Back Organizer",
    price: 21.99,
    category: "truck",
    type: "truck-interior",
    image: "images/products/steering-wheel.svg",
    description: "Multi-pocket organizer with tablet holder for the cab.",
    details: "Keeps paperwork, tools and snacks organized and off the floor.",
    features: ["9 pockets", "Tablet sleeve", "Adjustable straps"],
    added: "2026-02-25",
    inStock: true,
  },

  /* ---------------------------------- TOOLS --------------------------------- */
  {
    id: "claw-hammer-16oz",
    name: "16 oz Fiberglass Claw Hammer",
    price: 17.99,
    category: "tools",
    type: "hand-tools",
    image: "images/products/hammer.svg",
    description: "Balanced hammer with shock-absorbing grip.",
    details: "Forged steel head and fiberglass handle reduce vibration and fatigue.",
    features: ["16 oz forged head", "Fiberglass handle", "Anti-vibration grip"],
    added: "2026-03-30",
    inStock: true,
  },
  {
    id: "home-auto-tool-kit",
    name: "Home & Auto Tool Kit (65 pc)",
    price: 54.99,
    category: "tools",
    type: "hand-tools",
    image: "images/products/tool-kit.svg",
    description: "The essential tools every driver should keep in the trunk.",
    details: "Includes sockets, ratchet, screwdrivers, pliers, tape measure and more in a sturdy carry case.",
    features: ["65 pieces", "Blow-molded case", "Chrome vanadium steel"],
    featured: true,
    added: "2026-08-28",
    inStock: true,
  },
  {
    id: "screwdriver-set-8pc",
    name: "Screwdriver Set (8 pc)",
    price: 19.99,
    category: "tools",
    type: "screwdrivers",
    image: "images/products/screwdriver.svg",
    description: "Phillips & flat-head drivers with magnetic tips.",
    details: "Comfortable two-material handles and hardened tips for long life.",
    features: ["4 Phillips + 4 slotted", "Magnetic tips", "Ergonomic handles"],
    added: "2026-06-10",
    inStock: true,
  },
  {
    id: "ratcheting-screwdriver",
    name: "Ratcheting Multi-Bit Screwdriver",
    price: 15.99,
    category: "tools",
    type: "screwdrivers",
    image: "images/products/screwdriver.svg",
    description: "12 bits stored in the handle, fast ratchet action.",
    details: "One driver for almost every screw in your car or home.",
    features: ["12 bits included", "Ratchet mechanism", "In-handle storage"],
    added: "2026-09-12",
    inStock: true,
  },
  {
    id: "combination-wrench-set",
    name: "Combination Wrench Set SAE & Metric",
    price: 42.99,
    oldPrice: 49.99,
    category: "tools",
    type: "wrenches",
    image: "images/products/wrench.svg",
    description: "22 wrenches in a roll-up pouch, 1/4\"–3/4\" and 8–19 mm.",
    details: "Polished chrome vanadium steel with 12-point box ends for a solid grip.",
    features: ["22 pieces", "SAE & metric", "Roll-up storage pouch"],
    featured: true,
    added: "2026-05-15",
    inStock: true,
    badge: "Sale",
  },
  {
    id: "adjustable-wrench-10",
    name: "10\" Adjustable Wrench",
    price: 13.99,
    category: "tools",
    type: "wrenches",
    image: "images/products/wrench.svg",
    description: "Wide-opening jaw with laser-etched scale.",
    details: "Smooth worm gear and a comfortable cushioned handle.",
    features: ["Opens to 1-1/4\"", "Laser-etched scale", "Cushion grip"],
    added: "2025-10-22",
    inStock: true,
  },
  {
    id: "pliers-set-3pc",
    name: "Pliers Set (3 pc)",
    price: 24.99,
    category: "tools",
    type: "pliers",
    image: "images/products/pliers.svg",
    description: "Slip-joint, long-nose and diagonal cutting pliers.",
    details: "Induction-hardened cutting edges and comfortable dual-material grips.",
    features: ["3 essential pliers", "Hardened edges", "Comfort grips"],
    added: "2026-04-03",
    inStock: true,
  },
  {
    id: "locking-pliers-10",
    name: "10\" Locking Pliers",
    price: 14.99,
    category: "tools",
    type: "pliers",
    image: "images/products/pliers.svg",
    description: "Clamp and hold with a quick-release lever.",
    details: "Ideal for stuck bolts and holding parts while you work.",
    features: ["Quick-release", "Adjustable jaw", "Alloy steel"],
    added: "2026-07-30",
    inStock: true,
  },
  {
    id: "digital-tire-pressure-gauge",
    name: "Digital Tire Pressure Gauge",
    price: 12.99,
    category: "tools",
    type: "tire-tools",
    image: "images/products/tire-gauge.svg",
    description: "Accurate readings in PSI, BAR and kPa with backlight.",
    details: "Check your tires in seconds, day or night. Correct pressure saves fuel and extends tire life.",
    features: ["0–150 PSI", "Backlit display", "Auto shut-off"],
    featured: true,
    added: "2026-09-21",
    inStock: true,
    badge: "New",
  },
  {
    id: "portable-tire-inflator",
    name: "Portable 12V Tire Inflator",
    price: 59.99,
    category: "tools",
    type: "tire-tools",
    image: "images/products/tire-gauge.svg",
    description: "Set your target PSI and it stops automatically.",
    details: "Plugs into your car's 12V socket. Includes adapters for bikes and balls.",
    features: ["Auto stop", "Digital display", "LED work light"],
    added: "2026-06-22",
    inStock: true,
  },
  {
    id: "tire-repair-kit",
    name: "Tire Plug Repair Kit",
    price: 18.49,
    category: "tools",
    type: "tire-tools",
    image: "images/products/tire-gauge.svg",
    description: "Fix punctures on the spot with T-handle tools and plugs.",
    details: "Includes reamer, insert tool, 30 plugs and lubricant in a compact case.",
    features: ["30 plugs", "T-handle tools", "Compact case"],
    added: "2026-01-07",
    inStock: true,
  },
  {
    id: "oil-funnel-drain-set",
    name: "Oil Change Funnel & Drain Pan Set",
    price: 22.99,
    category: "tools",
    type: "maintenance",
    image: "images/products/oil-maintenance.svg",
    description: "Mess-free oil changes with a 15 qt drain pan and funnel.",
    details: "Leak-proof drain pan with spout plus a flexible-neck funnel.",
    features: ["15 qt pan", "Flexible funnel", "Spill-proof spout"],
    added: "2026-05-08",
    inStock: true,
  },
  {
    id: "oil-filter-wrench",
    name: "Universal Oil Filter Wrench",
    price: 11.99,
    category: "tools",
    type: "maintenance",
    image: "images/products/oil-maintenance.svg",
    description: "Adjustable 3-jaw wrench fits filters 2-1/2\" to 4\".",
    details: "Works with a 3/8\" ratchet for tight engine bays.",
    features: ["Fits 63–102 mm", "3/8\" drive", "Self-adjusting jaws"],
    added: "2026-03-14",
    inStock: true,
  },
  {
    id: "hydraulic-floor-jack",
    name: "2-Ton Hydraulic Floor Jack",
    price: 89.99,
    category: "tools",
    type: "maintenance",
    image: "images/products/floor-jack.svg",
    description: "Low-profile jack for quick tire changes at home.",
    details: "Lifts from 3.5\" to 13\" with a smooth pump action. Includes a padded saddle.",
    features: ["2-ton capacity", "Low profile", "Safety overload valve"],
    added: "2026-08-08",
    inStock: true,
  },
];
